# configuration files
# using YAML format,see more: https://yaml.org/
# required PyYAML module
# this file use indentation to indicate hierarchy

# data entry is the data file name list used for fit
data:
  # 4-momentum order of final particles in dat files [option]
  # the `finals` in `particle` will be used by default.
  # it is necessary when dat files has momentum out of final particles
  dat_order: [B, C, D]
  # basic data files, every line is `E px py pz` as 4-momentum of a particle,
  # and every m lines group as m final particls
  data: ["data/data4600_new.dat"]
  # data weight file, each line for a weight
  # data_weight: ["data/data_weight.dat"]
  # phase space data for normalize amplitude
  phsp: ["data/PHSP4600_new.dat"]
  # phase space weight file, each line for a weight
  # phsp_weight: ["data/phsp_weight.dat"]
  # phase space without efficiencies, used for calculating fit fraction.
  # phsp_noeff: ["data/PHSP4600_noeff.dat"]
  # much more phase space, used for plotting
  # phsp_plot: ["data/PHSP4600_plot.dat"]
  # optional weight background data, need bg_weight
  bg: ["data/bg4600_new.dat"]
  # background weight
  bg_weight: 0.731
  # inject MC in data
  # inmc: ["data/inMC.dat"]
  # inject_ratio: 0.01
  # float_inmc_ratio_in_pdf: False
  # whether boost data to center mass frame first
  # center_mass: True
  # cached data file
  # cached_data: "data/all_data.npy"
  # data_charge: ["data/data4600_cc.dat"] # charge conjugation condition same as weight

# `decay` describe the decay structure, each node can be a list of particle name
decay:
  # each entry is a list of direct decay particle, or a list or the list.
  # `dec_file` entry for loading `*.dec` files will be supported in the feature.
  # `-` is often used for list in yaml
  A:
    # for example A -> R_CD + B, R_CD -> C + D
    # the optional `key: value` mean option parameters of the decay
    # note there, R1 is overrated by `particle` entry as R1 and R11
    - [R_CD, B, model: default]
    - - R_BD
      - C
      - model: "default"
    - - R_BC
      - D
  # set l_list to allow only l=0
  # -   [ NR(BC)SP, D, curve_style: "g-", {has_barrier_factor: False, l_list: [0]}]
  # -   [B, C, D, curve_style: "darkgreen"]
  R_CD:
    - C
    - D
  R_BD: [B, D]
  R_BC: [B, C]
  # set l_list to allow only l=1
  # NR(BC)SP: [B, C, {has_barrier_factor: False, l_list: [1]}]

# `particle` describe the particle included
# top, finals, include are used as keywords
particle:
  # top decay particle
  $top:
    A:
      J: 1 # spin, use 1/2 or 0.5 for half spin
      P: -1 # parity, alias: `Par`
      spins: [-1, 1] # list of possible of spin-projected quantum numbers
  # final particles
  $finals:
    B:
      J: 1
      P: -1
    C:
      J: 1
      P: -1
    D:
      J: 0
      P: -1
  # map for possible resonances in the same position
  # each entry is a list of resonances id [option]
  # include detailed parameters defined in `Resonances.yml`
  $include: Resonances.sample.yml
  R_BD:
    - D2_2460p
    - D1_2430p
    - D1_2420p
  R_BC: [Zc_4025, Zc_4160]
  # by default the node is `name: [name]`
  # set `[]` for particle which is not in real decays,
  # just used for calculating angle data.
  R_CD: []
  # NR(BC)SP: {J: 1, P: -1, model: one}

# The following config is used for DecayChain
# decay_chain:
#   $all:
#      is_cp: True

# constrains for params [WIP]
constrains:
  # particle:
  #   equal:
  #     mass: [[D1_2430p, D1_2430]]
  decay: { fix_chain_idx: 0, fix_chain_val: 1 }
  # fix_var:
  #   "A->R_CD.BR_CD->C.D_total_0r": 1.0
  # var_range:
  #   "A->R_CD.BR_CD->C.D_total_0r": [1.0, null]
  # var_equal:
  #   -  ["A->R_CD.BR_CD->C.D_total_0r", "A->R_BD.CR_BD->B.D_total_0r"]

# plot describe the configuration of plotting 1-d data distribution
plot:
  # plot configuration TODO
  config:
    bins: 50
  # invariant mass
  mass:
    R_CD:
      # label of display
      # use `$$` for latex math
      display: "$M_{CD}$"
      # upper_ylim: 200
      # trans: x*x
    R_BD:
      display: "$M_{BD}$"
    R_BC:
      display: "$M_{BC}$"
  # helicity angle
  angle:
    # If it named as `[.../]A/R_BC`, it refer to the  decay A -> R_BC ... in the decay chain has A and R_BC,
    # the angle is determined by the last 2 particles, the other order is random.
    # for example, D->E+F in [A->R_BC+D, D->E+F, R_BC->B+C] is `R_BC/D/E` or `A/R_BC/D/E` or `R_BC/A/D/E`
    A/R_CD:
      # include "alpha, cos(beta), gamma", # add `cos` for cos(beta)
      alpha:
        display: "$\\phi_{1}$" # the default is "A/0:$\alpha$"
      cos(beta):
        display: "$\\cos(\\theta_1)$" # the default is "A/0:$\beta$"
        range: [-1, 1] # range for plot
    A/R_BD:
      alpha:
        display: "$\\phi_{2}$"
      cos(beta):
        display: "$\\cos(\\theta_2)$"
    A/R_BC:
      alpha:
        display: "$\\phi_{3}$"
      cos(beta):
        display: "$\\cos(\\theta_3)$"
    R_BC/B:
      alpha:
        display: "$\\phi_{11}$"
      cos(beta):
        display: "$\\cos(\\theta_{11})$"
    R_CD/C:
      alpha:
        display: "$\\phi_{1}$"
      cos(beta):
        display: "$\\cos(\\theta_{21})$"
    R_BD/B:
      alpha:
        display: "$\\phi_{1}$"
      cos(beta):
        display: "$\\cos(\\theta_{31})$"
  # 2D plot
  2Dplot:
    m_R_CD & m_R_BC:
      display: "$M_{CD}$ vs $M_{BC}$"
      plot_figs: ["data", "sideband", "fitted"]
